wandb_version: 1

C:
  desc: null
  value: 1.0
class_weight:
  desc: null
  value: null
dual:
  desc: null
  value: false
fit_intercept:
  desc: null
  value: true
intercept_scaling:
  desc: null
  value: 1
l1_ratio:
  desc: null
  value: null
max_iter:
  desc: null
  value: 100
multi_class:
  desc: null
  value: auto
n_jobs:
  desc: null
  value: null
penalty:
  desc: null
  value: l2
random_state:
  desc: null
  value: 42
solver:
  desc: null
  value: liblinear
tol:
  desc: null
  value: 0.0001
verbose:
  desc: null
  value: 0
warm_start:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699303708.545734
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.3
      5: 0.15.12
      8:
      - 4
      - 5
      10:
      - 5
      13: darwin-arm64
    viz:
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
      roc:
        id: wandb/roc/v1
        historyFieldSettings:
          x-axis: _step
          key: roc
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
test_size:
  desc: null
  value: 0.15
train_len:
  desc: null
  value: 99535
test_len:
  desc: null
  value: 36259
