wandb_version: 1

C:
  desc: null
  value: 1.0
class_weight:
  desc: null
  value: null
dual:
  desc: null
  value: false
fit_intercept:
  desc: null
  value: true
intercept_scaling:
  desc: null
  value: 1
l1_ratio:
  desc: null
  value: null
max_iter:
  desc: null
  value: 100
multi_class:
  desc: null
  value: auto
n_jobs:
  desc: null
  value: null
penalty:
  desc: null
  value: l2
random_state:
  desc: null
  value: 42
solver:
  desc: null
  value: liblinear
tol:
  desc: null
  value: 0.0001
verbose:
  desc: null
  value: 0
warm_start:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.12
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1699303088.307644
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.15.12
      8:
      - 4
      - 5
      13: darwin-arm64
